### ISSUE TITLE
 plugin: unknown plugin type: log4shell 

### ISSUE THREAD

**Issue by JamborJan** [traefik/plugin-log4shell#1]
I'm running `traefik:v2.5.4` on a Docker standalone host. I'm getting this error when creating the middle ware:

```log
 plugin: unknown plugin type: log4shell 
```

Interesting part of the traefik compose yaml:

```yaml
  traefik:
    image: traefik:v2.5.4
    restart: always
    command:
      - "--accesslog"
      - "--log.level=INFO"
      ...
      - "--experimental.plugins.log4shell.modulename=github.com/traefik/plugin-log4shell"
      - "--experimental.plugins.log4shell.version=v0.1.2"
      ...
```

Interesting part of the apps compose yaml:

```yaml
    ...
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.your.domain.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=mytlschallenge"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app.middlewares=log4shellMw@docker"
```

Am I doing anything wrong?
