### ISSUE TITLE
Mem Leak?

### ISSUE THREAD

**Issue by rjchicago** [traefik/plugin-log4shell#4]
Is there a possible memory leak with this plugin, or with the overall Traefik plugin system?

We're running Traefik 2.5.1 with the log4shell plugin (0.1.2) on 8 different Swarms since Dec 20 (~2 weeks). In one Swarm, Traefik is now using 30GB memory each (5 replicas). In another Swarm, Traefik is using 2GB memory each (5 replicas). The remaining 6 Swarms are seeing relatively normal memory usage - although, these past 2 weeks would also have seen much lower request volume.

### Memory
~60 nodes, 8 Swarms, memory usage over 4 weeks:
![image](https://user-images.githubusercontent.com/382450/147986939-84736246-35ca-4051-96a5-adc952363c8e.png)

I don't see anything glaring in the logs.

#### `middlewares.yml`

``` yml
http:
  middlewares:
    compress:
      compress: {}
    plugin-log4shell:
      plugin:
        log4shell:
          errorCode: "200"
```

#### `traefik.yml`

``` yml
# Traefik Config 2.x

pilot:
  token: "***********************************"

experimental:
  plugins:
    log4shell:
      moduleName: "github.com/traefik/plugin-log4shell"
      version: "v0.1.2"

# Entrypoints configuration
entryPoints:
  metrics:
    address: ':8084'
  http:
    address: ':80'
    forwardedHeaders:
      insecure: true
    http:
      middlewares:
        - compress@file
        - plugin-log4shell@file
...
```
