### ISSUE TITLE
Question about plugin

### ISSUE THREAD

**Issue by mushuthecat** [traefik/plugin-log4shell#6]
Hi,

Thanks for you job.

I have one question, i have setup your plugin using traefik.yml:

```
log4shell:
          modulename: github.com/traefik/plugin-log4shell
          version: v0.1.2
```
 
And dynamic.yml  :

```
log4shell-foo:
            plugin:
                log4shell:
                    errorCode: 200
```

My Traefik dashbord seems to be ok 👍 

![image](https://user-images.githubusercontent.com/83928911/150660946-05cafdde-017d-4f55-95fd-91a59ab34416.png)

It works perfectly, but how does it work ? can i see some logs about the "scan" ? 
Do i have to download some file into my traefik folder  to make it works ? can you give me more detail to be sure that im realy using your plugin ?

Regards
